---
  - name: Tap to cask drivers
    homebrew_tap:
      name: homebrew/cask-drivers
      state: 'present'

  - name: Install from cask
    homebrew_cask:
      name: [
        '1password',
        'adobe-creative-cloud',
        'alfred',
        'cleanapp',
        'controlplane',
        'dropbox',
        'docker',
        'dockstation',
        'firefox',
        'google-chrome',
        'google-featured-photos',
        'imageoptim',
        'iterm2',
        'istat-menus',
        'java',
        'karabiner-elements',
        'logitech-options',
        'macdown',
        'plex-media-server',
        'slack',
        'station',
        'spotify',
        'transmit',
        'vlc',
        'virtualbox',
        'visual-studio-code',
        'wunderlist',
        'zoomus'
      ]
      state: present
    ignore_errors: yes
